### PR TITLE
style: ensure consistent code formatting

### PR DESCRIPTION
**Pull request by michaeladler**
Enforce a consistent code style by formatting the code using [black](https://github.com/psf/black) and integrating black into the CI pipeline.

Notes: 

- I only added `skip-string-normalization` to the configuration because there are a lot of strings using single quotes which would be rewritten.
- I changed the line length to be conformant with flake8 (black by default enforces 88 whereas flake8 wants 79)

In general it's preferred to use the defaults of black to have a (somewhat) uniform codestyle across most Python projects. I'm happy to incorporate any feedback you might have. Consider this a first draft :)

### CODE REVIEW

**Comment by bufferoverflow** [comment]
That's a nice addition! btw. we started to use [Ruff](https://docs.astral.sh/ruff/) instead of black on many projects, maybe something to consider here as well.

**Comment by michaeladler** [comment]
Thanks @bufferoverflow for the suggestion to use Ruff. I heard about it some time ago but then forgot because back then, it was still in a very early stage. It's great that it has progressed so much. I went ahead and replaced Black and Flake8 with Ruff. I'm not sure, but I think Pylint could also be dropped now.

**Comment by bufferoverflow** [comment]
@michaeladler Yes, I would suggest to drop Pylint.

**Comment by fmoessbauer** [comment]
> @michaeladler Yes, I would suggest to drop Pylint.

That's fine for me as well.

BTW: do we have a similar tool for the JS part?

**Comment by bufferoverflow** [comment]
for JavaScript code I would recommend https://prettier.io/ and https://eslint.org/

**Comment by michaeladler** [comment]
I went ahead and also added prettier. I initially chose tabWidth to be 4 because I only looked at the JS files but the HTML and CSS files seem to be formatted with 2 spaces instead of 4. So I think we should use the default of tabWdith 2. What do you think @fmoessbauer?

**Comment by fmoessbauer** [comment]
> I went ahead and also added prettier.

Thanks!

> I initially chose tabWidth to be 4 because I only looked at the JS files but the HTML and CSS files seem to be formatted with 2 spaces instead of 4.

IMHO code with tabWidth 2 is really hard to read. I prefer to stay with 4 for the code. For other parts like the CSS, I have no strong feeling.

**Comment by michaeladler** [comment]
Ok then for consistency reasons I'd suggest to keep the setting globally at 4 (as it currently is in the PR).

**Comment by michaeladler** [comment]
Yep it's ready

**Comment by fmoessbauer** [comment]
@michaeladler One thing I noticed is that ruff is not yet packaged for debian bookworm (in sid it is). "black" is packaged, though. Are the formattings quite different between both tools? I don't want to rely on a component that is only distributed by pypi.

**Comment by michaeladler** [comment]
Thanks to static linking, everyone can use ruff :laughing: I noticed that we can drop the pylint annotations in the code (making me realize that ruff and pylint are not equivalent, so we might reconsider dropping them). This results in black and ruff having the same code formatting style (they even claim to be equivalent). With Trixie being released in 2025, this might be an acceptable intermediate state, but I don't have a strong opinion on that, so I'm also fine with using black in CI (or both :laughing:).

**Comment by fmoessbauer** [comment]
> Thanks to static linking, everyone can use ruff 😆 

That does not help, as we don't want to pull things together manually. We have distros for that reason.

> I noticed that we can drop the pylint annotations in the code (making me realize that ruff and pylint are not equivalent, so we might reconsider dropping pylint).

Either we drop pylint AND the annotations, or we keep both. As you prefer.

> This results in black and ruff having the same code formatting style (they even claim to be equivalent). With Trixie being released in 2025, this might be an acceptable intermediate state

Hmm... no. With black we have a tool that is already packaged.

> I'm also fine with using black in CI (or both 😆).

Please use black, and sorry for the back and forth.

**Comment by nejch** [comment]
You guys are really overthinking this for one python module with 300 lines of code :sweat_smile:

black and ruff would both be dev dependencies, so you would normally track them as python deps because your end users should never care about them. Both are pypi packages and you also shouldn't need to care about distro specifics of installing them. Which btw you already do in CI in this PR for the other linters :)

But I'm just adding to the back and forth, sorry. Just something for later. Ideally you'd have a pyproject.toml for you dev deps and pin the dependencies properly so there are no surprises. I can open a follow-up PR for that after this one is merged :+1:

**Comment by fmoessbauer** [comment]
> You guys are really overthinking this for one python module with 300 lines of code 😅

I'm happy that the whole extension fits in around 600LoC :smile: 

> black and ruff would both be dev dependencies, so you would normally track them as python deps because your end users should never care about them.

I still prefer to track them as distro dependencies, but that's probably a matter of taste.

Both are pypi packages and you also shouldn't need to care about distro specifics of installing them. Which btw you already do in CI in this PR for the other linters :)

Actually no. We just install `fsfe-reuse` via pip. Nitpick :smile: 

> Ideally you'd have a pyproject.toml for you dev deps and pin the dependencies properly so there are no surprises.

I thought about this as well - not for linting, but for properly distributing this. This would properly solve the interpreter path issue discussed in https://github.com/siemens/linux-entra-sso/pull/43. And it would make packaging easier.

I can open a follow-up PR for that after this one is merged 👍

That is much appreciated. If you have time, I'm happy to review it.

**Comment by bufferoverflow** [comment]
I agree with @nejch having a `pyproject.toml` makes sense. and I think it would be worth to add a `package.json` file as well.

**Comment by nejch** [comment]
Ah sorry yes,  I meant the existing reuse linter :+1: but for me that's a bit weird mixing two ways to install them, as different distros install different versions causing mismatching formatting and rules between local devs and CI. It's not really something I see in OSS Python projects. Either way, best not to complain and I'll open a PR yes! :slightly_smiling_face:

**Comment by fmoessbauer** [comment]
Thanks for the fixes and the patience. Applied!

**Review by fmoessbauer — APPROVED** [review]

**Pull request merged**
