### PR TITLE
Small improvements of our CI

### PR DESCRIPTION
**Pull request by fmoessbauer**
- fix warnings regarding missing tags
- add build provenance

### CODE REVIEW

**Review by jan-kiszka — APPROVED** [review]
Looks good.

BTW, which elements of / information about the build that are not under the control of someone requesting attestation will be signed here?

**Comment by fmoessbauer** [comment]
> BTW, which elements of / information about the build that are not under the control of someone requesting attestation will be signed here?

On non-release builds, we attest the generated zip / xpi artifacts. This does not include any external state. On release builds, we attest the signed xpi we get back from Mozilla (which cannot be reproduced for obvious reasons). In the end, that just attests that exactly that artifact was created as part of the CI pipeline run.

**Comment by jan-kiszka** [comment]
To my understanding, it's not you who attest anything here (no personal keys involved), it's GitHub. And I'm asking for who they control that no one else can generate similarly looking certificates.

**Comment by fmoessbauer** [comment]
> To my understanding, it's not you who attest anything here (no personal keys involved), it's GitHub

Well... they use OIDC with GitHub as identity provider to request a short lived certificate on behalf of you (the one who triggered the pipeline). The details are found in https://docs.sigstore.dev/signing/overview/.

As long as GitHub as identity provider is trustworthy, these signatures are related to your identity.

**Comment by jan-kiszka** [comment]
IOW, your identity name in combination with the requester (GitHub) are outside of the control of others running similar pipelines or issuing such signing requests directly.

**Comment by fmoessbauer** [comment]
> IOW, your identity name in combination with the requester (GitHub) are outside of the control of others running similar pipelines or issuing such signing requests directly.

Exactly.

**Pull request merged**
